import { db } from '../lib/db'

const CIT = 'cmmzovtuu0008qkvu6u4ayhzs'
const CAS = 'cmmzovtv10009qkvur7tude03'

// subject code → { title, units, hoursPerWeek, type, reqRoom }
// We define a master catalog first, then assign semester/year per program
const CATALOG: Record<string, { title: string; units: number; hoursPerWeek: number; type: 'LECTURE'|'LABORATORY'; reqRoom: string[] }> = {
  // GEC
  'GEC01': { title: 'The Life and Works of Rizal', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC02': { title: 'Understanding the Self', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC03': { title: 'Readings in the Philippine History', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC04': { title: 'The Contemporary World', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC05': { title: 'Mathematics in the Modern World', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC06': { title: 'Purposive Communication', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC07': { title: 'Art Appreciation', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC08': { title: 'Science Technology and Society', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC09': { title: 'Ethics', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC10': { title: 'Kontekstwalisadong Komunikasyon sa Filipino', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC11': { title: "Filipino sa Iba't Ibang Disiplina", units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC12': { title: 'Dalumat ng/sa Filipino', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC13': { title: 'Literature of the Philippines', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEC14': { title: 'Literature of the World', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  // GEL
  'GEL01': { title: 'Environmental Science', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEL07': { title: 'Gender and Society', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'GEL10': { title: 'Philippine Popular Culture', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  // PATHFit
  'PATHFit01': { title: 'Movement Skill Training', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PATHFit02': { title: 'Fitness and Wellness Activities', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PATHFit03': { title: 'Rhythmic Activities and/or Sports', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PATHFit04': { title: 'Recreational Activities', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  // NST
  'NST01':  { title: 'National Service Training Program 1', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'NSTP01': { title: 'National Service Training Program 1', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'NSTP1':  { title: 'National Service Training Program 1', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'NST02':  { title: 'National Service Training Program 2', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'NSTP02': { title: 'National Service Training Program 2', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'NSTP2':  { title: 'National Service Training Program 2', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  // Shared CIT
  'IIT01':   { title: 'Introduction to Information Technology', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'IIT01L':  { title: 'Introduction to Information Technology Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB','LABORATORY'] },
  'COM01a':  { title: 'Computer Programming', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM01aL': { title: 'Computer Programming Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'IND01':   { title: 'Industrial Drawing', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'IND01L':  { title: 'Industrial Drawing Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CHM01a':  { title: 'Chemistry for Industrial Technologist', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CHM01aL': { title: 'Chemistry for Industrial Technologist Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'PHY01a':  { title: 'Physics for Industrial Technologist', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PHY01aL': { title: 'Physics for Industrial Technologist Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MAT04a':  { title: 'Comprehensive Mathematics', units: 5, hoursPerWeek: 5, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'RES01a':  { title: 'Project Study 1 with Intellectual Property Rights', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'RES01aL': { title: 'Project Study 1 with Intellectual Property Rights Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'RES02a':  { title: 'Project Study 2', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'RES02aL': { title: 'Project Study 2 Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'PSY11a':  { title: 'Industrial Psychology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY11':   { title: 'Industrial Psychology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'F-SY11a': { title: 'Industrial Psychology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MTM01':   { title: 'Materials Technology Management', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MGT02':   { title: 'Technopreneurship', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'IEN08a':  { title: 'Quality Control and Assurance', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'IEN04a':  { title: 'Industrial Organization and Management', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'IEN11a':  { title: 'Production Management', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'FLO01':   { title: 'Foreign Language', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
}

// Add program-specific subjects to catalog
const PROG_CATALOG: Record<string, { title: string; units: number; hoursPerWeek: number; type: 'LECTURE'|'LABORATORY'; reqRoom: string[] }> = {
  // AFT
  'AFT01':  { title: 'Occupational Safety and Health', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT02':  { title: 'Sewing Machine Operations Maintenance & Basic Apparel', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT02L': { title: 'Sewing Machine Operations Maintenance & Basic Apparel Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AFT03':  { title: 'Fundamentals of Apparel Construction', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT03L': { title: 'Fundamentals of Apparel Construction Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AFT04':  { title: 'Introduction to Fashion Designing', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT04L': { title: 'Introduction to Fashion Designing Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AFT05':  { title: 'Advanced Apparel Construction', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT05L': { title: 'Advanced Apparel Construction Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AFT06':  { title: 'Fashion Arts and Apparel Accessories', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT06L': { title: 'Fashion Arts and Apparel Accessories Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AFT07':  { title: 'Creative Costume Design and Construction', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT07L': { title: 'Creative Costume Design and Construction Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AFT08':  { title: 'Pattern Standardization and Grading', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT08L': { title: 'Pattern Standardization and Grading Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AFT09':  { title: 'Tailoring', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT09L': { title: 'Tailoring Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AFT10':  { title: 'Advanced Pattern Drafting/Designing', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT10L': { title: 'Advanced Pattern Drafting/Designing Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AFT11':  { title: 'Home Furnishing and Fashion Accessories', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT11L': { title: 'Home Furnishing and Fashion Accessories Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AFT12':  { title: 'Fabrics and Thread: Selection and Usage', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT13':  { title: 'Production Management in Garment Industry', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT14':  { title: 'Draping Fashion Modeling and Fashion Show with Hair Styling and Artistic Make-up', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AFT14L': { title: 'Draping Fashion Modeling and Fashion Show with Hair Styling and Artistic Make-up Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  // AIT
  'AIT01':  { title: 'Occupational Safety and Health', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT02':  { title: 'Fundamentals of Automotive Technology', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT03':  { title: 'Automotive Electrical System', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT04':  { title: 'Automotive Electronics', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT04L': { title: 'Automotive Electronics Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AIT05':  { title: 'Small Engine Repair and Motorcycle Servicing', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT05L': { title: 'Small Engine Repair and Motorcycle Servicing Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AIT06':  { title: 'Car Care Servicing Emission Control and Tune-up', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT06L': { title: 'Car Care Servicing Emission Control and Tune-up Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AIT07':  { title: 'Body Repair and Painting', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT07L': { title: 'Body Repair and Painting Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AIT08':  { title: 'Power Train and Conversion System', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT08L': { title: 'Power Train and Conversion System Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AIT09':  { title: 'Automotive LPG System', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT09L': { title: 'Automotive LPG System Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AIT10':  { title: 'Automotive Air Conditioning', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT10L': { title: 'Automotive Air Conditioning Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AIT11':  { title: 'Engine Overhauling and Performance Testing', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT11L': { title: 'Engine Overhauling and Performance Testing Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AIT12':  { title: 'Hybrid and Electric Vehicle', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT12L': { title: 'Hybrid and Electric Vehicle Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AIT13':  { title: 'Driving Education', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT13L': { title: 'Driving Education Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AIT14':  { title: 'Body Management and Under Chassis Electronic Control System', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT14L': { title: 'Body Management and Under Chassis Electronic Control System Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AIT15':  { title: 'Automotive Computer-Aided Design', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'AIT15L': { title: 'Automotive Computer-Aided Design Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'AIT16':  { title: 'Electronics Engine Management System', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
}

Object.assign(PROG_CATALOG, {
  // CPT
  'CPT02a':  { title: 'Fundamentals of Electricity and Electronics', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CPT02aL': { title: 'Fundamentals of Electricity and Electronics Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CPT04':   { title: 'Computer System and Hardware', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CPT04L':  { title: 'Computer System and Hardware Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'CPT05':   { title: 'Logic and Switching Theory', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CPT05L':  { title: 'Logic and Switching Theory Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CPT01':   { title: 'Occupational Safety and Health', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CPT08a':  { title: 'Computer Installation and Servicing', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CPT08aL': { title: 'Computer Installation and Servicing Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE15':   { title: 'Computer Networking 1', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE15L':  { title: 'Computer Networking 1 Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'CPT10':   { title: 'Specialized Technology 1', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CPT10L':  { title: 'Specialized Technology 1 Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CPT14':   { title: 'Specialized Technology 2', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CPT14L':  { title: 'Specialized Technology 2 Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CPT16':   { title: 'Advanced Programming', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CPT16L':  { title: 'Advanced Programming Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'CPT17':   { title: 'Embedded System', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CPT17L':  { title: 'Embedded System Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CPT18':   { title: 'Platform Technologies', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CPT18L':  { title: 'Platform Technologies Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'CPT19':   { title: 'Information Management', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CPT19L':  { title: 'Information Management Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE28':   { title: 'Emerging Technologies', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE28L':  { title: 'Emerging Technologies Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'CPT11a':  { title: 'Seminar in Computer Technology', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CPT11aL': { title: 'Seminar in Computer Technology Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ITE13a':  { title: 'Professional Issues in Computing', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  // CUL
  'CUL01':   { title: 'Occupational Safety and Health', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL02':   { title: 'Food Safety and Sanitation', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL02L':  { title: 'Food Safety and Sanitation Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CUL03':   { title: 'Kitchen Essential and Basic Food Preparation', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL04':   { title: 'Advanced Food Preparation', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL04L':  { title: 'Advanced Food Preparation Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CUL05':   { title: 'Food Styling and Design', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL05L':  { title: 'Food Styling and Design Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CUL06':   { title: 'Advanced Garde Manger', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL06L':  { title: 'Advanced Garde Manger Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CUL07':   { title: 'Introduction to Bakery and Pastry', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL07L':  { title: 'Introduction to Bakery and Pastry Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CUL08':   { title: 'Quantity Food Production Planning and Management', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL08L':  { title: 'Quantity Food Production Planning and Management Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CUL09':   { title: 'Wine Beverage and Mixology', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL09L':  { title: 'Wine Beverage and Mixology Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CUL10':   { title: 'Catering and Events Simulation', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL10L':  { title: 'Catering and Events Simulation Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CUL11':   { title: 'Nutrition and Food Trends', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL12':   { title: 'Philippine Regional Cuisine and Asian Cuisine', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL12L':  { title: 'Philippine Regional Cuisine and Asian Cuisine Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CUL13':   { title: 'Western Cuisine', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL13L':  { title: 'Western Cuisine Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'CUL14':   { title: 'Plant-based Cooking', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CUL14L':  { title: 'Plant-based Cooking Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
})

Object.assign(PROG_CATALOG, {
  // ELX
  'ELX01':  { title: 'Occupational Safety and Health', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX02':  { title: 'Electronic Devices 1', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX02L': { title: 'Electronic Devices 1 Laboratory', units: 6, hoursPerWeek: 6, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELX03':  { title: 'Electronics Communication 1', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX03L': { title: 'Electronics Communication 1 Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELX04':  { title: 'Electronics CAD', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX04L': { title: 'Electronics CAD Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELX05':  { title: 'Electronic Devices 2', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX05L': { title: 'Electronic Devices 2 Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELX06':  { title: 'Electronic Communications 2', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX06L': { title: 'Electronic Communications 2 Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELX07':  { title: 'Digital Electronics', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX07L': { title: 'Digital Electronics Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELX08':  { title: 'Instrumentation and Process Control', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX08L': { title: 'Instrumentation and Process Control Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELX09':  { title: 'Sensor Technology', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX09L': { title: 'Sensor Technology Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELX10':  { title: 'Electronic Laws and Standards', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX11':  { title: 'Multimedia Systems', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX11L': { title: 'Multimedia Systems Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELX12':  { title: 'Industrial Electronics', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX12L': { title: 'Industrial Electronics Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELX13':  { title: 'Electro-Pneumatic Systems', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELX13L': { title: 'Electro-Pneumatic Systems Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT17':  { title: 'Electro-Pneumatic Systems (Advanced)', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT17L': { title: 'Electro-Pneumatic Systems (Advanced) Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT18':  { title: 'Instrumentation and Process Control (Advanced)', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT18L': { title: 'Instrumentation and Process Control (Advanced) Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  // ELT (Electrical)
  'ELT01':  { title: 'Occupational Safety and Health', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT02':  { title: 'Electricity and Electronics Principles', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT02L': { title: 'Electricity and Electronics Principles Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT03':  { title: 'DC Circuits', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT03L': { title: 'DC Circuits Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT04':  { title: 'Shop Process Tools and Equipment', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT04L': { title: 'Shop Process Tools and Equipment Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT05':  { title: 'Philippine Electrical Code', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT06':  { title: 'Residential Wiring System', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT06L': { title: 'Residential Wiring System Laboratory', units: 6, hoursPerWeek: 6, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT07':  { title: 'AC Circuits', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT07L': { title: 'AC Circuits Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT08':  { title: 'Industrial Wiring System', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT08L': { title: 'Industrial Wiring System Laboratory', units: 6, hoursPerWeek: 6, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT09':  { title: 'Electrical Instruments and Measurement', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT09L': { title: 'Electrical Instruments and Measurement Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT10':  { title: 'Electrical Machines', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT10L': { title: 'Electrical Machines Laboratory', units: 6, hoursPerWeek: 6, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT11':  { title: 'Transmission and Distribution System', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT11L': { title: 'Transmission and Distribution System Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT12':  { title: 'Industrial Motor Controllers', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT12L': { title: 'Industrial Motor Controllers Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT13':  { title: 'Power Production and Management Systems', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT13L': { title: 'Power Production and Management Systems Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT14':  { title: 'Logic Circuits', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT14L': { title: 'Logic Circuits Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT15':  { title: 'Electrical Computer Aided Design', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT15L': { title: 'Electrical Computer Aided Design Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELT16':  { title: 'Programmable Logic Controllers', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ELT16L': { title: 'Programmable Logic Controllers Laboratory', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
})

Object.assign(PROG_CATALOG, {
  // MET
  'MET01':  { title: 'Occupational Health and Safety', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET02':  { title: 'Basic Arc and Gas Welding Practices', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET02L': { title: 'Basic Arc and Gas Welding Practices Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MET03':  { title: 'Bench Working Pipefitting and Pipe Bending', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET03L': { title: 'Bench Working Pipefitting and Pipe Bending Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MET04':  { title: 'Metallurgy and Heat Treatment', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET04L': { title: 'Metallurgy and Heat Treatment Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MET05':  { title: 'Machining I: Turning and Shaping', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET05L': { title: 'Machining I: Turning and Shaping Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MET06':  { title: 'Mechanical CAD', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET06L': { title: 'Mechanical CAD Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MET07':  { title: 'Machine Design for Technology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET08':  { title: 'Machining II: Milling and Surface Grinding', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET08L': { title: 'Machining II: Milling and Surface Grinding Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MET09':  { title: 'Basic CNC Lathe', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET09L': { title: 'Basic CNC Lathe Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MET10':  { title: 'Principle of Tool & Die and Pattern Development', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET10L': { title: 'Principle of Tool & Die and Pattern Development Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MET11':  { title: 'Basic CNC Milling', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET11L': { title: 'Basic CNC Milling Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MET12':  { title: 'Advance Computer Numerical Control (CNC)', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET12L': { title: 'Advance Computer Numerical Control (CNC) Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MET13':  { title: 'Pneumatic Electropneumatic and Hydraulic', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MET13L': { title: 'Pneumatic Electropneumatic and Hydraulic Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  // PMT
  'PMT01':  { title: 'Occupational Safety and Health', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PMT02':  { title: 'Fundamentals of Visual Communication', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PMT02L': { title: 'Fundamentals of Visual Communication Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'PMT03':  { title: 'Introduction to Printing Techniques', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PMT03L': { title: 'Introduction to Printing Techniques Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'PMT04':  { title: 'Introduction to Media Technology', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PMT04L': { title: 'Introduction to Media Technology Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'PMT05':  { title: 'Sustainability and Environment', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PMT05L': { title: 'Sustainability and Environment Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'PMT06':  { title: 'Visual Graphic Design', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PMT06L': { title: 'Visual Graphic Design Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'PMT07':  { title: 'Digital Printing', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PMT07L': { title: 'Digital Printing Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'PMT08':  { title: 'Digital Photography and Image Processing', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PMT08L': { title: 'Digital Photography and Image Processing Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'PMT09':  { title: 'Commercial and Packaging Design', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PMT09L': { title: 'Commercial and Packaging Design Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'PMT10':  { title: 'Industrial Printing', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PMT10L': { title: 'Industrial Printing Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'PMT11':  { title: 'Digital Print Production', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PMT11L': { title: 'Digital Print Production Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'PMT12':  { title: 'Printing Press Management', units: 1, hoursPerWeek: 1, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PMT12L': { title: 'Printing Press Management Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  // BSInfoTech
  'ITE01':  { title: 'Introduction to Computing', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE01L': { title: 'Introduction to Computing Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE02':  { title: 'Computer Programming 1', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE02L': { title: 'Computer Programming 1 Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE03':  { title: 'Human Computer Interaction', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE04':  { title: 'Discrete Mathematics', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE05':  { title: 'Computer Programming 2', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE05L': { title: 'Computer Programming 2 Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE06':  { title: 'Visual Graphic Design', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE06L': { title: 'Visual Graphic Design Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE07':  { title: 'Database Management Systems 1', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE07L': { title: 'Database Management Systems 1 Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE08':  { title: 'Data Structures and Algorithms', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE08L': { title: 'Data Structures and Algorithms Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE09':  { title: 'Quantitative Methods', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE09L': { title: 'Quantitative Methods Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE10':  { title: 'Front-End Development', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE10L': { title: 'Front-End Development Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE11':  { title: 'Database Management Systems 2', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE11L': { title: 'Database Management Systems 2 Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE12':  { title: 'Information Assurance and Security', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE13':  { title: 'IT Social and Professional Issues', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE14':  { title: 'Systems Analysis and Design', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE16':  { title: 'Object-Oriented Programming', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE16L': { title: 'Object-Oriented Programming Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE17':  { title: 'Cognate/Professional Course 1 (Elective)', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE17L': { title: 'Cognate/Professional Course 1 (Elective) Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE18':  { title: 'Cognate/Professional Course 2 (Elective)', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE18L': { title: 'Cognate/Professional Course 2 (Elective) Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE19':  { title: 'Computer Organization Architecture and Logic', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE19L': { title: 'Computer Organization Architecture and Logic Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE20':  { title: 'Computer Networking 2', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE20L': { title: 'Computer Networking 2 Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE21':  { title: 'Operating Systems', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE21L': { title: 'Operating Systems Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE22':  { title: 'IT Project Management', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE23':  { title: 'Capstone Project 1', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE24':  { title: 'Cognate/Professional Course 3 (Elective)', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE24L': { title: 'Cognate/Professional Course 3 (Elective) Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE25':  { title: 'Cognate/Professional Course 4 (Elective)', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE25L': { title: 'Cognate/Professional Course 4 (Elective) Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE26':  { title: 'Seminars in IT Trends', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LECTURE_ROOM'] },
  'ITE27':  { title: 'User Experience Design', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE29':  { title: 'Capstone Project 2', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE30':  { title: 'IT Entrepreneurship', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE31':  { title: 'Systems Administration and Maintenance', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE31L': { title: 'Systems Administration and Maintenance Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'ITE32':  { title: 'Data Mining and Analytics', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ITE32L': { title: 'Data Mining and Analytics Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
})

Object.assign(PROG_CATALOG, {
  // CAS majors
  'COM01': { title: 'Introduction to Communication Media', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM02': { title: 'Communication Theory', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM04': { title: 'Communication Culture and Society', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM05': { title: 'Communication Media Laws and Ethics', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM09': { title: 'Risk Disaster & Humanitarian Communication', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM11': { title: 'Journalism Principles and Practices', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM12': { title: 'Broadcasting Principles and Practices', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM13': { title: 'Social Media Principles and Practices', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM16': { title: 'Creative Writing', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CSH01': { title: 'Sociology of Language Communication', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM03': { title: 'Communication Research', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM08': { title: 'Development Communication', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM10': { title: 'Knowledge Management', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM17': { title: 'Introduction to Theater Arts', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM18': { title: 'Organizational Culture and Communication', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'RES01': { title: 'Methods of Research', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM14': { title: 'Advertising Principles and Practices', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM15': { title: 'Introduction to Film', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM19': { title: 'Behavioral and Social Change Communication', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CSH02': { title: 'Language Gender and Media', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'RES02': { title: 'Thesis Writing', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM06': { title: 'Communication Planning', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CSH03': { title: 'Discourse and Communication', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CSH04': { title: 'Foreign Language', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'CSH05': { title: 'Principles of Teaching with Media and Technology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'COM07': { title: 'Communication Management', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  // BAHist
  'HST01':  { title: 'Intro to the Study & Writing History', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HSTE1':  { title: 'Geography', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'FLS01':  { title: 'Elementary Spanish', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HST02':  { title: 'Pre-16th Century Philippines', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HST03':  { title: 'Philippine Cultural History', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HST04':  { title: 'Survey of Asian Civilizations', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'FLS02':  { title: 'Advanced Spanish', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HST05':  { title: 'Survey of Western Civilizations', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HST06':  { title: 'Philosophy of History', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HST07':  { title: 'Nationalism and Revolution', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'FLS03':  { title: 'Reading and Translation in Spanish', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HST08':  { title: 'Historical Methodology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HST09':  { title: 'Mainland Southeast Asia', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HST10':  { title: 'Modern East Asia', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HSTE2':  { title: 'Heritage Studies', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'FLS04':  { title: 'Obras Literarias delos Heroes', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HST11':  { title: 'Senior Thesis', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HST12':  { title: 'History of USA', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HSTE3':  { title: 'Indigenous Studies', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'HSTE4':  { title: 'Museology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  // BSBio
  'BOT01':  { title: 'General Botany', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BOT01L': { title: 'General Botany Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ZOO01':  { title: 'General Zoology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'ZOO01L': { title: 'General Zoology Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BCH01':  { title: 'Organic Molecules', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO01':  { title: 'General Ecology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO01L': { title: 'General Ecology Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BCH02':  { title: 'Analytical Methods for Biology', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BCH02L': { title: 'Analytical Methods for Biology Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BIO02':  { title: 'Genetics', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO02L': { title: 'Genetics Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BPH00':  { title: 'Biophysics', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BPH00L': { title: 'Biophysics Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BIO03':  { title: 'Comparative Anatomy', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO03L': { title: 'Comparative Anatomy Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BCH03':  { title: 'Biomolecules', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BCH03L': { title: 'Biomolecules Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MCB01':  { title: 'General Microbiology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MCB01L': { title: 'General Microbiology Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BST01':  { title: 'Statistical Biology', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BST01L': { title: 'Statistical Biology Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MCB02':  { title: 'Food Safety', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MCB02L': { title: 'Food Safety Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BIO04':  { title: 'General Physiology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO04L': { title: 'General Physiology Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BIO05':  { title: 'Systematics', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO05L': { title: 'Systematics Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BIO101': { title: 'Thesis I', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO06':  { title: 'Developmental Biology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO06L': { title: 'Developmental Biology Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BIO07':  { title: 'Cell and Molecular Biology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO07L': { title: 'Cell and Molecular Biology Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BIO08':  { title: 'Marine Biology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO08L': { title: 'Marine Biology Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELE01':  { title: 'Elective 1 (Bioinformatics)', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO102': { title: 'Thesis II', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO10':  { title: 'Introduction to Philippine Wildlife', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO10L': { title: 'Philippine Wildlife Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BIO11':  { title: 'Ethnobotany', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO11L': { title: 'Ethnobotany Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'ELE02':  { title: 'Elective 2 (Teaching Methods)', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO103': { title: 'Thesis III', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO13':  { title: 'Microbial Ecology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO13L': { title: 'Microbial Ecology Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BIO14':  { title: 'Evolutionary Biology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'BIO14L': { title: 'Evolutionary Biology Laboratory', units: 2, hoursPerWeek: 2, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'BIO110': { title: 'Practicum', units: 3, hoursPerWeek: 3, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  // BSMath
  'MAT04a': { title: 'Calculus I', units: 4, hoursPerWeek: 4, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT09':  { title: 'Fundamental Concept of Computing I', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT09L': { title: 'Fundamental Concept of Computing I Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'MAT05a': { title: 'Calculus II', units: 4, hoursPerWeek: 4, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT11':  { title: 'Fundamental Concepts of Mathematics', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT15':  { title: 'Abstract Algebra I', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT10':  { title: 'Fundamental Concepts of Computing II', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT10L': { title: 'Fundamental Concepts of Computing II Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'MAT06a': { title: 'Calculus III', units: 4, hoursPerWeek: 4, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PHY01':  { title: 'General Physics I', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PHY01L': { title: 'General Physics I Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MAT16':  { title: 'Linear Algebra', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PHY02':  { title: 'General Physics II', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PHY02L': { title: 'General Physics II Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['LABORATORY'] },
  'MAT19':  { title: 'Probability', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT18':  { title: 'Advanced Calculus I', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT33':  { title: 'Real Analysis', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT14':  { title: 'Theory of Interest', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT20':  { title: 'Statistical Theory', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT20L': { title: 'Statistical Theory Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'MAT07':  { title: 'Differential Equations I', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT07L': { title: 'Differential Equations I Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'MAT34':  { title: 'Topology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT32':  { title: 'Modern Geometry', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT24':  { title: 'Mathematical Modelling', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT24L': { title: 'Mathematical Modelling Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'MAT23':  { title: 'Operations Research I', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT23L': { title: 'Operations Research I Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  'MAT35':  { title: 'Complex Analysis', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT30':  { title: 'Numerical Analysis', units: 2, hoursPerWeek: 2, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'MAT30L': { title: 'Numerical Analysis Laboratory', units: 1, hoursPerWeek: 1, type: 'LABORATORY', reqRoom: ['COMPUTER_LAB'] },
  // BAPsych
  'PSY01':     { title: 'Introduction to Psychology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY02':     { title: 'Psychological Statistics', units: 5, hoursPerWeek: 5, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY03':     { title: 'Bio Psychological', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY04':     { title: 'Developmental Psychology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY05':     { title: 'Theories of Personality', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY06':     { title: 'Experimental Psychology', units: 5, hoursPerWeek: 5, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY07':     { title: 'Cognitive Psychology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY10':     { title: 'Social Psychology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY09':     { title: 'Abnormal Psychology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY08':     { title: 'Field Methods in Psychology', units: 5, hoursPerWeek: 5, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY12':     { title: 'Psychological Assessment', units: 5, hoursPerWeek: 5, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY13':     { title: 'Culture and Psychology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY14':     { title: 'Research 1', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY-ELE01': { title: 'Introduction to Clinical Psychology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY15':     { title: 'Research 2', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY-ELE02': { title: 'Strategic Human Resource Management', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY-ELE03': { title: 'Practicum in Psychology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
  'PSY-ELE04': { title: 'Integrative Course in Psychology', units: 3, hoursPerWeek: 3, type: 'LECTURE', reqRoom: ['LECTURE_ROOM'] },
})

// Merge all catalog entries
const ALL_CATALOG = { ...CATALOG, ...PROG_CATALOG }

type Entry = { code: string; semester: 'FIRST'|'SECOND'; year: number; deptId: string }

// Exact curriculum per program — only these codes, exactly these semester/year placements
const CURRICULUM: Entry[] = [
  // ── BAComm ────────────────────────────────────────────────────────────────
  ...(['GEC02','GEC06','GEC08','GEC09','GEC10','PATHFit01','NST01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CAS})),
  ...(['GEC01','GEC03','GEC05','GEC07','GEC13','PATHFit02','NST02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CAS})),
  ...(['COM01','COM02','COM04','COM05','GEC04','GEC14','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CAS})),
  ...(['COM09','COM11','COM12','COM13','COM16','CSH01','GEC11','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CAS})),
  ...(['COM03','COM08','COM10','COM17','COM18','GEC12'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CAS})),
  ...(['RES01','COM14','COM15','COM19','CSH02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CAS})),
  ...(['RES02','COM06','CSH03','CSH04','CSH05'] as const).map(c=>({code:c,semester:'FIRST' as const,year:4,deptId:CAS})),
  ...(['COM07'] as const).map(c=>({code:c,semester:'SECOND' as const,year:4,deptId:CAS})),
  // ── BAHist ────────────────────────────────────────────────────────────────
  ...(['GEC02','GEC03','GEC05','GEC06','PATHFit01','NSTP1'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CAS})),
  ...(['GEC01','GEC04','GEC08','GEC10','GEC09','PATHFit02','NSTP2'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CAS})),
  ...(['GEC07','GEC13','HST01','HSTE1','FLS01','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CAS})),
  ...(['GEC11','HST02','HST03','HST04','FLS02','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CAS})),
  ...(['HST05','HST06','HST07','FLS03','GEC14','GEC12'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CAS})),
  ...(['HST08','HST09','HST10','HSTE2','FLS04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CAS})),
  ...(['HST11','HST12','HSTE3'] as const).map(c=>({code:c,semester:'FIRST' as const,year:4,deptId:CAS})),
  ...(['HSTE4'] as const).map(c=>({code:c,semester:'SECOND' as const,year:4,deptId:CAS})),
  // ── BSBio ─────────────────────────────────────────────────────────────────
  ...(['GEC08','GEC10','BOT01','BOT01L','ZOO01','ZOO01L','PATHFit01','NSTP1'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CAS})),
  ...(['GEC02','GEC03','GEC05','BCH01','BIO01','BIO01L','PATHFit02','NSTP2'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CAS})),
  ...(['GEC07','BCH02','BCH02L','BIO02','BIO02L','BPH00','BPH00L','BIO03','BIO03L','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CAS})),
  ...(['GEC09','GEC11','GEC13','BCH03','BCH03L','MCB01','MCB01L','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CAS})),
  ...(['GEC04','GEC06','BST01','BST01L','MCB02','MCB02L','BIO04','BIO04L','BIO05','BIO05L','BIO101'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CAS})),
  ...(['GEC01','BIO06','BIO06L','BIO07','BIO07L','BIO08','BIO08L','ELE01','BIO102'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CAS})),
  ...(['BIO10','BIO10L','BIO11','BIO11L','ELE02','BIO103'] as const).map(c=>({code:c,semester:'FIRST' as const,year:4,deptId:CAS})),
  ...(['BIO13','BIO13L','BIO14','BIO14L','BIO110'] as const).map(c=>({code:c,semester:'SECOND' as const,year:4,deptId:CAS})),
  // ── BSMath ────────────────────────────────────────────────────────────────
  ...(['MAT04a','MAT09','MAT09L','GEC01','GEC05','GEC08','PATHFit01','NST01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CAS})),
  ...(['MAT05a','MAT11','GEC02','GEC06','GEC10','PATHFit02','NST02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CAS})),
  ...(['MAT15','MAT10','MAT10L','MAT06a','PHY01','PHY01L','GEC07','GEC13','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CAS})),
  ...(['MAT16','PHY02','PHY02L','MAT19','MAT18','GEC09','GEC11','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CAS})),
  ...(['MAT33','MAT14','MAT20','MAT20L','MAT07','MAT07L','GEC04'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CAS})),
  ...(['MAT34','MAT32','MAT24','MAT24L','GEC03','MAT23','MAT23L','RES01'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CAS})),
  ...(['MAT35','MAT30','MAT30L','RES02'] as const).map(c=>({code:c,semester:'FIRST' as const,year:4,deptId:CAS})),
  // ── BAPsych ───────────────────────────────────────────────────────────────
  ...(['GEC02','GEC08','GEC10','GEC04','PATHFit01','NST01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CAS})),
  ...(['GEC01','GEC03','GEC05','GEC06','PSY01','PATHFit02','NST02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CAS})),
  ...(['GEC07','PSY02','PSY03','PSY04','PATHFit03','GEC13'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CAS})),
  ...(['GEC09','GEC11','PSY05','PSY06','PSY07','PATHFit04','GEC14'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CAS})),
  ...(['PSY10','PSY09','PSY08','PSY11'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CAS})),
  ...(['PSY12','PSY13','PSY14','GEC12'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CAS})),
  ...(['PSY-ELE01','PSY15','PSY-ELE02'] as const).map(c=>({code:c,semester:'FIRST' as const,year:4,deptId:CAS})),
  ...(['PSY-ELE03','PSY-ELE04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:4,deptId:CAS})),
]

// CIT programs
CURRICULUM.push(
  // ── BSIT-Garm (AFT) ───────────────────────────────────────────────────────
  ...(['AFT01','AFT02','AFT02L','AFT03','AFT03L','GEC01','GEC04','COM01a','COM01aL','PATHFit01','NST01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CIT})),
  ...(['AFT04','AFT04L','AFT05','AFT05L','GEC02','GEC05','IIT01','IIT01L','IND01','IND01L','PATHFit02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CIT})),
  ...(['AFT06','AFT06L','AFT07','AFT07L','AFT08','AFT08L','CHM01a','CHM01aL','GEC08','GEC09','GEL07','GEL10','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CIT})),
  ...(['AFT09','AFT09L','PHY01a','PHY01aL','MAT04a','GEC03','GEC06','GEC07','GEL01','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CIT})),
  ...(['AFT10','AFT10L','AFT11','AFT11L','RES01a','RES01aL','PSY11a','MTM01','IEN08a','IEN04a'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CIT})),
  ...(['AFT12','AFT13','AFT14','AFT14L','RES02a','RES02aL','FLO01','MGT02','IEN11a'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CIT})),
  // ── BSIT-Auto (AIT) ───────────────────────────────────────────────────────
  ...(['AIT01','AIT02','AIT03','CHM01a','IND01','GEC02','GEC05','PATHFit01','NST01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CIT})),
  ...(['AIT04','AIT04L','AIT05','AIT05L','AIT06','AIT06L','IIT01','IIT01L','COM01a','COM01aL','MAT04a','PATHFit02','NSTP02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CIT})),
  ...(['AIT07','AIT07L','AIT08','AIT08L','AIT09','AIT09L','AIT10','AIT10L','PHY01a','PHY01aL','GEL01','GEC09','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CIT})),
  ...(['AIT11','AIT11L','AIT12','AIT12L','AIT13','AIT13L','GEC07','GEC03','GEC04','MTM01','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CIT})),
  ...(['AIT14','AIT14L','RES01a','RES01aL','PSY11a','GEC06','GEL07','GEC08','MGT02','IEN11a'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CIT})),
  ...(['AIT15','AIT15L','AIT16','RES02a','RES02aL','FLO01','GEL10','GEC01','IEN08a','IEN04a'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CIT})),
  // ── BSIT-Comp (CPT) ───────────────────────────────────────────────────────
  ...(['CPT02a','CPT02aL','CPT04','CPT04L','CPT05','CPT05L','IIT01','IIT01L','COM01a','COM01aL','GEC01','GEC04','PATHFit01','NST01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CIT})),
  ...(['CPT01','CPT08a','CPT08aL','ITE15','ITE15L','IND01','IND01L','GEC02','GEC05','PATHFit02','NSTP02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CIT})),
  ...(['CPT10','CPT10L','CHM01a','CHM01aL','MAT04a','GEC08','GEC09','GEL07','GEL10','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CIT})),
  ...(['CPT14','CPT14L','CPT16','CPT16L','PHY01a','PHY01aL','GEC03','GEC06','GEC07','GEL01','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CIT})),
  ...(['CPT17','CPT17L','CPT18','CPT18L','CPT19','CPT19L','RES01a','RES01aL','PSY11a','FLO01','MTM01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CIT})),
  ...(['ITE28','ITE28L','CPT11a','CPT11aL','RES02a','RES02aL','ITE13a','IEN08a','IEN04a','MGT02','IEN11a'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CIT})),
  // ── BSIT-Food (CUL) ───────────────────────────────────────────────────────
  ...(['CUL01','CUL02','CUL02L','CUL03','GEC01','GEC04','COM01a','COM01aL','PATHFit01','NSTP01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CIT})),
  ...(['CUL04','CUL04L','CUL05','CUL05L','GEC02','GEC05','IIT01','IIT01L','IND01','IND01L','PATHFit02','NSTP02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CIT})),
  ...(['CUL06','CUL06L','CUL07','CUL07L','CHM01a','GEC08','GEC09','GEL07','MTM01','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CIT})),
  ...(['CUL08','CUL08L','CUL09','CUL09L','PHY01a','PHY01aL','MAT04a','GEC03','GEC06','GEC07','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CIT})),
  ...(['CUL10','CUL10L','CUL11','CUL12','CUL12L','RES01a','RES01aL','GEL10','PSY11a','MGT02','IEN11a'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CIT})),
  ...(['CUL13','CUL13L','CUL14','CUL14L','RES02a','RES02aL','GEL01','FLO01','IEN08a','IEN04a'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CIT})),
  // ── BSIT-Eltx (ELX) ───────────────────────────────────────────────────────
  ...(['ELX01','ELX02','ELX02L','ELX03','ELX03L','ELX04','ELX04L','IND01','IND01L','GEC05','COM01a','COM01aL','PATHFit01','NST01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CIT})),
  ...(['ELX05','ELX05L','ELX06','ELX06L','ELX07','ELX07L','MAT04a','CHM01a','IIT01','IIT01L','PATHFit02','NSTP02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CIT})),
  ...(['ELX08','ELX08L','ELX09','ELX09L','ELX10','PHY01a','PHY01aL','GEL01','GEC09','MTM01','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CIT})),
  ...(['ELX11','ELX11L','ELX12','ELX12L','ELX13','ELX13L','GEC07','GEC04','IEN08a','IEN04a','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CIT})),
  ...(['ELT17','ELT17L','RES01a','RES01aL','GEC02','GEC03','GEL07','GEC08','GEL10','F-SY11a'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CIT})),
  ...(['ELT18','ELT18L','RES02a','RES02aL','GEC01','FLO01','GEC06','MGT02','IEN11a'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CIT})),
  // ── BSIT-Elec (ELT) ───────────────────────────────────────────────────────
  ...(['ELT01','ELT02','ELT02L','ELT03','ELT03L','ELT04','ELT04L','ELT05','ELT06','ELT06L','GEC05','IND01','IND01L','PATHFit01','NSTP01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CIT})),
  ...(['ELT07','ELT07L','ELT08','ELT08L','ELT09','ELT09L','ELT10','ELT10L','CHM01a','IIT01','IIT01L','COM01a','COM01aL','PATHFit02','NSTP02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CIT})),
  ...(['ELT11','ELT11L','ELT12','ELT12L','ELT13','ELT13L','GEL01','MAT04a','GEC09','PHY01a','PHY01aL','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CIT})),
  ...(['ELT14','ELT14L','ELT15','ELT15L','ELT16','ELT16L','GEC04','GEC07','MTM01','IEN08a','IEN04a','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CIT})),
  ...(['ELT17','ELT17L','RES01a','RES01aL','GEC02','GEC03','GEL07','GEC08','GEL10','F-SY11a'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CIT})),
  ...(['ELT18','ELT18L','RES02a','RES02aL','GEC01','FLO01','GEC06','MGT02','IEN11a'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CIT})),
  // ── BSIT-Mech (MET) ───────────────────────────────────────────────────────
  ...(['MET01','MET02','MET02L','MET03','MET03L','IND01','IND01L','GEC02','GEC05','PATHFit01','NSTP01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CIT})),
  ...(['MET04','MET04L','MET05','MET05L','IIT01','IIT01L','COM01a','COM01aL','GEC01','GEC04','PATHFit02','NSTP02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CIT})),
  ...(['MET06','MET06L','MET07','MAT04a','PHY01a','PHY01aL','GEC07','GEL01','GEC03','GEC06','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CIT})),
  ...(['MET08','MET08L','MET09','MET09L','CHM01a','GEC09','GEL07','GEL10','GEC08','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CIT})),
  ...(['MET10','MET10L','MET11','MET11L','RES01a','RES01aL','MTM01','MGT02','IEN11a'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CIT})),
  ...(['MET12','MET12L','MET13','MET13L','RES02a','RES02aL','FLO01','PSY11a','IEN08a','IEN04a'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CIT})),
  // ── BSIT-Print (PMT) ──────────────────────────────────────────────────────
  ...(['PMT01','PMT02','PMT02L','PMT03','PMT03L','GEC01','GEC04','COM01a','COM01aL','PATHFit01','NSTP01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CIT})),
  ...(['PMT04','PMT04L','PMT05','PMT05L','GEC05','GEC02','IIT01','IIT01L','IND01','IND01L','PATHFit02','NSTP02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CIT})),
  ...(['PMT06','PMT06L','PHY01a','PHY01aL','MAT04a','GEC03','GEC06','GEC07','GEL01','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CIT})),
  ...(['PMT07','PMT07L','PMT08','PMT08L','CHM01a','GEC08','GEC09','GEL07','GEL10','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CIT})),
  ...(['PMT09','PMT09L','PMT10','PMT10L','RES01a','RES01aL','IEN08a','PSY11','IEN11a'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CIT})),
  ...(['PMT11','PMT11L','PMT12','PMT12L','RES02a','RES02aL','MTM01','IEN04a','MGT02','FLO01'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CIT})),
  // ── BSInfoTech (ITE) ──────────────────────────────────────────────────────
  ...(['GEC04','GEC05','GEC08','GEC10','ITE01','ITE01L','PATHFit01','NSTP01'] as const).map(c=>({code:c,semester:'FIRST' as const,year:1,deptId:CIT})),
  ...(['GEC02','GEC03','GEC06','GEC11','ITE02','ITE02L','PATHFit02','NSTP02'] as const).map(c=>({code:c,semester:'SECOND' as const,year:1,deptId:CIT})),
  ...(['GEC01','GEC09','ITE03','ITE04','ITE05','ITE05L','ITE06','ITE06L','ITE07','ITE07L','PATHFit03'] as const).map(c=>({code:c,semester:'FIRST' as const,year:2,deptId:CIT})),
  ...(['GEC07','GEC13','ITE08','ITE08L','ITE09','ITE09L','ITE10','ITE10L','ITE11','ITE11L','PATHFit04'] as const).map(c=>({code:c,semester:'SECOND' as const,year:2,deptId:CIT})),
  ...(['ITE12','ITE13','ITE14','ITE15','ITE15L','ITE16','ITE16L','ITE17','ITE17L','ITE18','ITE18L'] as const).map(c=>({code:c,semester:'FIRST' as const,year:3,deptId:CIT})),
  ...(['ITE19','ITE19L','ITE20','ITE20L','ITE21','ITE21L','ITE22','ITE23','ITE24','ITE24L','ITE25','ITE25L'] as const).map(c=>({code:c,semester:'SECOND' as const,year:3,deptId:CIT})),
  ...(['ITE26','ITE27','ITE28','ITE28L','ITE29','ITE30','ITE31','ITE31L','ITE32','ITE32L'] as const).map(c=>({code:c,semester:'FIRST' as const,year:4,deptId:CIT})),
)

async function main() {
  console.log('Clearing schedule entries, teaching loads, and subjects...')
  await db.scheduleEntry.deleteMany({})
  await db.teachingLoad.deleteMany({})
  await db.subject.deleteMany({})
  console.log('Cleared.')

  // Collect unique codes to insert (first occurrence wins for semester/year)
  const seen = new Map<string, Entry>()
  for (const e of CURRICULUM) {
    if (!seen.has(e.code)) seen.set(e.code, e)
  }

  console.log(`Inserting ${seen.size} unique subjects...`)
  let inserted = 0
  for (const [code, entry] of seen) {
    const meta = ALL_CATALOG[code]
    if (!meta) {
      console.warn(`  WARNING: No catalog entry for code "${code}" — skipping`)
      continue
    }
    await db.subject.create({
      data: {
        code,
        title: meta.title,
        units: meta.units,
        hoursPerWeek: meta.hoursPerWeek,
        type: meta.type,
        semester: entry.semester,
        year: entry.year,
        departmentId: entry.deptId,
        requiredRoomType: meta.reqRoom as any,
      },
    })
    inserted++
  }
  console.log(`Done. Inserted ${inserted} subjects.`)
}

main().catch(console.error).finally(() => db.$disconnect())
