/**
 * College of Administration, Business, Hospitality and Accountancy (CABHA) —
 * transcribed from CURRICULUM_CABHA.docx.
 *
 * Normalisations applied to the printed codes (everything else is verbatim):
 *   - PATHFit0n / PATHFIT0n / NST0n / NSTP0n / HIST0n → PATHFit0n / NSTPn (CAS codes; BSA prints
 *     its NSTP rows as HIST01 / HIST02 — the titles are "National Service Training Program")
 *   - BPA GEL01 "Living in the IT Era"        → GEL04 (added to CAS by the seed runner)
 *   - BPA GEL02 "Philippine Popular Culture"  → GEL10 (the CAS code for that title)
 *   - BPA GEL04 "The Entrepreneurial Mind"    → GEL05 (added to CAS by the seed runner)
 *   - OJT / Practicum is printed under Lec (BSA), under Lab (BSBA-FM/MM, BSHM, BPA) and under
 *     both (BSBA-HRM). It is one dept-wide code, so it is entered as a 6-unit lecture
 *     "Practicum / Work Integrated Learning" everywhere.
 *   - BSBA-HRM Year 3 First Semester prints no units at all; 3 units each is assumed.
 * Codes shared by several programs (BAC0x, BME01/02, BNA01/02, IBT01, HBO01, RES01/02, OJT …)
 * become department-wide subjects with a majority title (e.g. BME01 "Operations Management
 * (TQM)", RES01 "Business Research (Methods of Research)", RES02 "Thesis (Paper Writing)").
 */
import { block, r, type CollegeCurriculum } from "./types"

export const CABHA: CollegeCurriculum = {
  college: "CABHA",
  department: "CABHA",
  programs: [
    {
      abbreviation: "BSA",
      name: "Bachelor of Science in Accountancy",
      blocks: [
        block(1, "FIRST", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("AEC13", "Financial Accounting and Reporting", 3),
          r("GEC06", "Purposive Communication", 3),
          r("AEC22", "Cost Accounting and Control", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC04", "The Contemporary World", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("AEC01", "Law on Obligations and Contracts", 3),
          r("AEC14", "Conceptual Framework and Accounting Standards", 3),
          r("GEC01", "The Life and Works of Rizal", 3),
          r("AEC15", "Intermediate Accounting 1", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
        ]),
        block(2, "FIRST", [
          r("GEC09", "Ethics", 3),
          r("GEC13", "Literature of the Philippines", 3),
          r("AEC26", "Income Taxation", 3),
          r("AEC16", "Intermediate Accounting 2", 3),
          r("AEC23", "Strategic Cost Management", 3),
          r("AEC02", "Business Laws and Regulations", 3),
          r("BME01", "Operations Management (TQM)", 3),
          r("AEC04", "Management Science", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC07", "Art Appreciation", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("AEC25", "Business Taxation", 3),
          r("AEC03", "Regulatory Framework and Legal Issues in Business", 3),
          r("AEC17", "Intermediate Accounting 3", 3),
          r("AEC10", "Governance, Business Ethics, Risk Management and Internal Control", 3),
          r("AEC18", "Financial Markets", 3),
          r("AEC12", "Economic Development", 3),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("AEC19", "Financial Management", 3),
          r("STA02", "Statistical Analysis with Software Application", 2, 1),
          r("AEC21", "IT Application Tools in Business", 2, 1),
          r("PrE01", "Auditing and Assurance Principles", 3),
          r("PrE02", "Auditing and Assurance: Concepts and Application 1", 3),
          r("PrE06", "Accounting for Special Transactions", 3),
          r("PrE07", "Accounting for Business Combinations", 3),
          r("AEC11", "Managerial Economics", 3),
        ]),
        block(3, "SECOND", [
          r("ELE02", "Operations Auditing", 3),
          r("RES01", "Business Research (Methods of Research)", 3),
          r("IBT01", "International Business and Trade", 3),
          r("PrE08", "Accounting for Government and Non-Profit Organizations", 3),
          r("PrE03", "Auditing and Assurance: Concepts and Applications 2", 3),
          r("PrE04", "Auditing and Assurance: Specialized Industries", 3),
          r("AEC20", "Accounting Information System", 2, 1),
          r("HBO01", "Human Behavior in Organization", 3),
        ]),
        block(4, "FIRST", [
          r("OJT", "Practicum / Work Integrated Learning", 6),
          r("RES02", "Thesis (Paper Writing)", 3),
        ]),
        block(4, "SECOND", [
          r("BME02", "Strategic Management", 3),
          r("AEC24", "Strategic Business Analysis", 3),
          r("ELE03", "Updates in Financial Reporting Standards", 3),
          r("ELE04", "Valuation Concept and Methods", 3),
          r("PrE05", "Auditing in a CIS Environment", 2, 1),
          r("INT01", "Integrated Accounting 1 (AFAR, FAR and Auditing)", 3),
          r("INT02", "Integrated Accounting 2 (Business Laws, Taxation and MAS)", 3),
        ]),
      ],
    },
    {
      abbreviation: "BSBA-HRM",
      name: "Bachelor of Science in Business Administration Major in Human Resource Management",
      blocks: [
        block(1, "FIRST", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("BAC05", "Human Resource Management", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
          r("BAC02", "Business Law", 3),
        ]),
        block(2, "FIRST", [
          r("GEC07", "Art Appreciation", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("BAC01", "Basic Microeconomics", 3),
          r("HRM01", "Administrative and Office Management", 3),
          r("BAC04", "Good Governance and Social Responsibility", 3),
          r("GEC13", "Literature of the Philippines", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC09", "Ethics", 3),
          r("BNA01", "Business Analytics Fundamentals with Introduction to Descriptive and Predictive Analytics", 3),
          r("BAC03", "Income Taxation", 3),
          r("HRM02", "Recruitment and Selection", 3),
          r("HRM03", "Training and Development", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("BME01", "Operations Management (TQM)", 3),
          r("IBT01", "International Business and Trade", 3),
          r("HRE05", "Project Management", 3),
          r("HRM04", "Labor Law and Legislations", 3),
          r("HRM05", "Compensation Administration", 3),
          r("HRE01", "Entrepreneurial Management", 3),
          r("BNA02", "Fundamentals of Prescriptive Analytics", 3),
        ]),
        block(3, "SECOND", [
          r("BME02", "Strategic Management", 3),
          r("HRM06", "Labor Relations and Negotiations", 3),
          r("HRE03", "Logistics Management", 3),
          r("HRE04", "Marketing Management", 3),
          r("HRE02", "Human Resource Information System (HRIS)", 3),
          r("RES01", "Business Research (Methods of Research)", 3),
        ]),
        block(4, "FIRST", [
          r("RES02", "Thesis (Paper Writing)", 3),
          r("HRM07", "Organizational Development", 3),
          r("PHM08", "Special Topics in HRM (with SAP)", 2, 1),
        ]),
        block(4, "SECOND", [
          r("OJT", "Practicum / Work Integrated Learning", 6),
        ]),
      ],
    },
    {
      abbreviation: "BSBA-FM",
      name: "Bachelor of Science in Business Administration Major in Financial Management",
      blocks: [
        block(1, "FIRST", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("BAC02", "Business Law", 3),
          r("BAC05", "Human Resource Management", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
        ]),
        block(2, "FIRST", [
          r("GEC07", "Art Appreciation", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("BAC01", "Basic Microeconomics", 3),
          r("FNM01", "Financial Management", 3),
          r("FNM03", "Banking and Financial Institutions", 3),
          r("GEC13", "Literature of the Philippines", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC09", "Ethics", 3),
          r("BAC03", "Income Taxation", 3),
          r("FNM04", "Monetary Policy and Central Banking", 3),
          r("FNM02", "Financial Analysis and Reporting", 3),
          r("BNA01", "Business Analytics Fundamentals with Introduction to Descriptive and Predictive Analytics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("BME01", "Operations Management (TQM)", 3),
          r("BAC04", "Good Governance and Social Responsibility", 3),
          r("FNM06", "Credit and Collection", 3),
          r("FNM05", "Investment and Portfolio Management", 3),
          r("FME01", "Entrepreneurial Management", 3),
          r("FME02", "Financial Controllership", 3),
          r("BNA02", "Fundamentals of Prescriptive Analytics", 3),
        ]),
        block(3, "SECOND", [
          r("BME02", "Strategic Management", 3),
          r("FNM07", "Capital Market", 3),
          r("FME03", "Cooperative Management", 3),
          r("FME04", "Global Finance", 3),
          r("RES01", "Business Research (Methods of Research)", 3),
          r("FME05", "Risk Management", 3),
        ]),
        block(4, "FIRST", [
          r("RES02", "Thesis (Paper Writing)", 3),
          r("IBT01", "International Business and Trade", 3),
          r("FME06", "Special Topics in Financial Management (with SAP)", 2, 1),
        ]),
        block(4, "SECOND", [
          r("OJT", "Practicum / Work Integrated Learning", 6),
        ]),
      ],
    },
    {
      abbreviation: "BSBA-MM",
      name: "Bachelor of Science in Business Administration Major in Marketing Management",
      blocks: [
        block(1, "FIRST", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("BAC05", "Human Resource Management", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
          r("BAC02", "Business Law", 3),
        ]),
        block(2, "FIRST", [
          r("GEC07", "Art Appreciation", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("BAC01", "Basic Microeconomics", 3),
          r("MKM05", "Marketing Management", 3),
          r("MKM02", "Product Management", 3),
          r("GEC13", "Literature of the Philippines", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC09", "Ethics", 3),
          r("PATHFit04", "Recreational Activities", 2),
          r("BNA01", "Business Analytics Fundamentals with Introduction to Descriptive and Predictive Analytics", 3),
          r("BAC03", "Income Taxation", 3),
          r("MKM03", "Distribution Management", 3),
          r("MKM04", "Retail Management", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
        ]),
        block(3, "FIRST", [
          r("BME01", "Operations Management (TQM)", 3),
          r("MKM08", "Advertising", 3),
          r("MKM01", "Pricing Strategy", 3),
          r("MKM06", "Marketing Research", 3),
          r("MME01", "Entrepreneurial Management", 3),
          r("MME02", "E-Commerce and Internet Marketing", 3),
          r("BNA02", "Fundamentals of Prescriptive Analytics", 3),
        ]),
        block(3, "SECOND", [
          r("BME02", "Strategic Management", 3),
          r("MKM07", "Professional Salesmanship", 3),
          r("MME03", "International Marketing", 3),
          r("IBT01", "International Business and Trade", 3),
          r("RES01", "Business Research (Methods of Research)", 3),
          r("BAC04", "Good Governance and Social Responsibility", 3),
        ]),
        block(4, "FIRST", [
          r("RES02", "Thesis (Paper Writing)", 3),
          r("MME05", "Services Marketing", 3),
          r("MME04", "Special Topics in Marketing Management (with SAP)", 2, 1),
        ]),
        block(4, "SECOND", [
          r("OJT", "Practicum / Work Integrated Learning", 6),
        ]),
      ],
    },
    {
      abbreviation: "BSHM",
      name: "Bachelor of Science in Hospitality Management",
      blocks: [
        block(1, "FIRST", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("THC01", "Macro Perspective of Tourism and Hospitality", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC07", "Art Appreciation", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("THC02", "Risk Management as Applied to Safety, Security and Sanitation", 3),
          r("THC03", "Micro Perspective of Tourism and Hospitality", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
        ]),
        block(2, "FIRST", [
          r("GEC08", "Science, Technology and Society", 3),
          r("GEC13", "Literature of the Philippines", 3),
          r("BME01a", "Operations Management in Tourism and Hospitality", 3),
          r("THC04", "Philippine Tourism, Culture, and Geography", 3),
          r("HPC01", "Fundamentals in Food Service Operations", 2, 1),
          r("HPC02", "Fundamentals in Lodging Operations", 2, 1),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC09", "Ethics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("HPC03", "Kitchen Essentials and Basic Food Preparation", 1, 2),
          r("HPC04", "Applied Business Tools and Technologies (PMS)", 2, 1),
          r("HPC05", "Foreign Language 1", 3),
          r("HME01", "Bar and Beverage Management", 2, 1),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("THC05", "Quality Service Management in Tourism and Hospitality", 3),
          r("THC06", "Tourism and Hospitality Marketing", 3),
          r("THC07", "Multicultural Diversity in Workplace for the Tourism Professionals", 3),
          r("HPC06", "Introduction to Meetings, Incentives, Conferences and Events Management (MICE)", 2, 1),
          r("HPC07", "Foreign Language 2", 3),
          r("HME02", "Gastronomy", 3),
          r("HME03", "Oenology", 2, 1),
        ]),
        block(3, "SECOND", [
          r("BME02a", "Strategic Management in Tourism and Hospitality", 3),
          r("THC08", "Professional Development and Applied Ethics", 3),
          r("THC09", "Entrepreneurship in Tourism and Hospitality", 3),
          r("THC10", "Legal Aspects in Tourism and Hospitality", 3),
          r("HPC08", "Ergonomics and Facilities Planning for the Hospitality Industry", 2, 1),
          r("HPC09", "Supply Chain Management in the Hospitality Industry", 3),
          r("HME04", "Menu Design and Revenue Management (Product Design and Merchandising)", 3),
        ]),
        block(4, "FIRST", [
          r("RES00", "Research in Hospitality", 2, 1),
          r("HME05", "Franchising (includes case studies)", 3),
        ]),
        block(4, "SECOND", [
          r("OJT", "Practicum / Work Integrated Learning", 6),
        ]),
      ],
    },
    {
      abbreviation: "BPA",
      name: "Bachelor of Science in Public Administration",
      blocks: [
        block(1, "FIRST", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("BPA01", "Introduction to Public Administration", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("BAC04", "Good Governance and Social Responsibility", 3),
          r("GEL04", "Living in the IT Era", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
        ]),
        block(2, "FIRST", [
          r("BPA20", "Philippine Administrative Thought and Institutions", 3),
          r("BME01", "Operations Management (TQM)", 3),
          r("GEC07", "Art Appreciation", 3),
          r("GEL10", "Philippine Popular Culture", 3),
          r("PSC01", "Sociology", 3),
          r("STA01", "Elementary Statistics", 3),
          r("GEC09", "Ethics", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("PAE01", "Voluntary Sector Management", 3),
          r("BPA21", "Ethics and Accountability in the Public Service", 3),
          r("BPA22", "Public Fiscal Administration", 3),
          r("GEL05", "The Entrepreneurial Mind", 3),
          r("BME02", "Strategic Management", 3),
          r("ACC01", "Basic Accounting", 3),
          r("BPA23", "Organization and Management", 3),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("BPA30", "Knowledge Management and ICT for Public Administration", 3),
          r("BPA31", "Public Accounting and Budgeting", 3),
          r("BPA32", "Office and Systems Management", 3),
          r("BPA33", "Local and Regional Governance", 3),
          r("BPA34", "Politics and Administration", 3),
          r("BPA35", "Special Topics for Public Administration", 3),
          r("PAE02", "Public Administration in a Changing World", 3),
        ]),
        block(3, "SECOND", [
          r("RES01", "Business Research (Methods of Research)", 3),
          r("BPA36", "Public Personnel Administration", 3),
          r("HBO01", "Human Behavior in Organization", 3),
          r("BPA37", "Administrative Law", 3),
          r("BPA38", "Public Policy and Program Administration", 3),
          r("BPA39", "Leadership and Decision Making", 3),
          r("PAE03", "Government Auditing", 3),
        ]),
        block(4, "FIRST", [
          r("BPM01", "Governance and Development", 3),
          r("PAE04", "Environmental Management", 3),
          r("PAE05", "Public Relations", 3),
          r("RES02", "Thesis (Paper Writing)", 3),
        ]),
        block(4, "SECOND", [
          r("OJT", "Practicum / Work Integrated Learning", 6),
        ]),
      ],
    },
  ],
}
