/**
 * College of Teacher Education (CTE) — transcribed from CURRICULUM_CTE.docx.
 *
 * Normalisations applied to the printed codes (everything else is verbatim):
 *   - PATHFIT0n / NSTPn / NST0n           → PATHFit0n / NSTPn (CAS codes; see canonicalCode)
 *   - GEL12 / GEL01 "Gender and Society"   → GEL07  (the CAS code for that title)
 *   - GEL04 "Living in the IT Era"         → GEL04  (added to CAS by the seed runner)
 *   - TECO1 → TEC01, AAFO1 → AAF01         (letter O typed for digit 0)
 *   - LING02 → LIN02                       (BSEd-Eng uses LIN01 / LIN03 around it)
 *   - BCAEd "ELE01 Solfege" → CAE-ELE01    (BEEd already uses ELE01 for a different subject)
 *   - PED11 Teaching Internship is printed under Lab for BSEd-Sci / BSEd-SS and under Lec
 *     elsewhere; it is one dept-wide code so it is entered as a 6-unit lecture everywhere.
 *   - ESS29 Internship is likewise entered as a 6-unit lecture (printed under Lab).
 *   - AAF01 Art Apprenticeship II sits in the BCAEd Mid-Year term → semester SUMMER.
 * Codes shared by several programs (PED*, FS001, FS002, TCC01, RES01/02, ET001, …) become
 * department-wide subjects; each program's own year/semester placement is carried by the
 * curriculum map (lib/curriculum-map.ts), not by the single stored year/semester.
 */
import { block, r, type CollegeCurriculum } from "./types"

export const CTE: CollegeCurriculum = {
  college: "CTE",
  department: "CTE",
  programs: [
    {
      abbreviation: "BCAEd",
      name: "Bachelor of Culture and Arts Education",
      blocks: [
        block(1, "FIRST", [
          r("CAED01", "Foundations of Culture and Arts Education", 3),
          r("CAED02", "Culture and Arts Education in Plural Societies", 3),
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("PED01", "The Child and Adolescent Learners and Learning Principles", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PED04", "Foundation of Special and Inclusive Education", 3),
          r("CAE-ELE01", "Solfege (Elective)", 3),
          r("CAE23", "Creative Industries as Culture and Arts Practice", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
        ]),
        block(2, "FIRST", [
          r("GEC09", "Ethics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("CAE03", "Perspective in Philippine Cultural Heritage", 3),
          r("CAE04", "The Philosophical and Historical Foundations of Creative Expressions in Sound I", 3),
          r("CAE05", "Visual Arts in Traditional Societies", 3),
          r("CAE06", "Foundations of Dance", 3),
          r("CAE07", "The Philosophical and Educational Foundations of Creative Drama", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC07", "Art Appreciation", 3),
          r("GEC12", "Dalumat ng/sa Filipino", 3),
          r("PED02", "The Teaching Profession", 3),
          r("PED03", "The Teacher and the Community, School Culture and Organizational Leadership", 3),
          r("CAE08", "The Philosophical and Historical Foundations of Creative Expressions in Sound II", 3),
          r("CAE09", "Contemporary Art in Various Contexts", 3),
          r("CAE10", "Philippine Traditional Dances", 3),
          r("CAE11", "Introduction to the Basic Elements of Drama and Theater Production", 3),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("PED05", "Facilitating Learner-Centered Teaching", 3),
          r("PED06", "Assessment in Learning 1", 3),
          r("PED08", "Technology for Teaching and Learning 1", 3),
          r("PED09", "The Teacher and the School Curriculum", 3),
          r("CAE12", "Music Pedagogy I (Teaching Methods in Music for K-G)", 3),
          r("CAE13", "Analysis and Critical Understanding of the Visual Arts", 3),
          r("CAE14", "International Dance and Other Forms", 3),
          r("CAE15", "Dramaturgy and Aesthetics in Philippine and Non-Philippine Theater Classics", 3),
        ]),
        block(3, "SECOND", [
          r("PED07", "Assessment in Learning 2", 3),
          r("PED10", "Building and Enhancing New Literacies Across the Curriculum", 3),
          r("CAE20", "Research I - Methods in Research (Arts and Culture Research)", 3),
          r("CAE22", "Technology for Teaching and Learning in Culture and Arts Education", 3),
          r("CAE16", "Teaching Methods in Music for Junior and Senior High School", 3),
          r("CAE17", "Teaching the Visual Arts", 3),
          r("CAE18", "Teaching Dance", 3),
          r("CAE19", "Principles and Practice of Teaching Drama", 3),
        ]),
        block(3, "SUMMER", [
          r("AAF01", "Art Apprenticeship II", 3),
        ]),
        block(4, "FIRST", [
          r("CAED21", "Research II - Culminating Project", 3),
          r("FS001", "Field Study 1", 3),
          r("FS002", "Field Study 2", 3),
          r("ICL01", "Intensive Course in Culture and Arts Education", 3),
        ]),
        block(4, "SECOND", [
          r("PED11", "Teaching Internship", 6),
        ]),
      ],
    },
    {
      abbreviation: "BEEd",
      name: "Bachelor of Elementary Education",
      blocks: [
        block(1, "FIRST", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("PED01", "The Child and Adolescent Learners and Learning Principles", 3),
          r("ELE16", "Content and Pedagogy in the Mother Tongue", 3),
          r("ELE17", "Good Manners and Right Conduct (Edukasyon sa Pagpapakatao)", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PED04", "Foundation of Special and Inclusive Education", 3),
          r("PED08", "Technology for Teaching and Learning 1", 3),
          r("ELE13", "Teaching PE and Health in the Elementary Grades", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
        ]),
        block(2, "FIRST", [
          r("GEC09", "Ethics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("PED05", "Facilitating Learner-Centered Teaching", 3),
          r("PED06", "Assessment in Learning 1", 3),
          r("PED09", "The Teacher and the School Curriculum", 3),
          r("ELE11", "Teaching Music in the Elementary Grades", 3),
          r("ELE12", "Teaching Arts in the Elementary Grades", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC07", "Art Appreciation", 3),
          r("GEC14", "Literature of the World", 3),
          r("PED02", "The Teaching Profession", 3),
          r("PED07", "Assessment in Learning 2", 3),
          r("PED10", "Building and Enhancing New Literacies Across the Curriculum", 3),
          r("ELE01", "Teaching Science in the Elementary Grades (Biology and Chemistry)", 3),
          r("ELE07", "Teaching Math in the Primary Grades", 3),
          r("ELE14", "Teaching English in the Elementary Grades (Language Arts)", 3),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("ELE02", "Teaching Science in the Elementary Grades (Physics, Earth, and Space Science)", 3),
          r("ELE03", "Teaching Social Studies in the Elementary Grades (Philippine History and Government)", 3),
          r("ELE05", "Pagtuturo ng Filipino sa Elementarya I (Estruktura at Gamit ng Wikang Filipino)", 3),
          r("ELE08", "Teaching Math in the Intermediate Grades", 3),
          r("ELE09", "Edukasyong Pantahanan at Pangkabuhayan 1", 3),
          r("ELE15", "Teaching English in the Elementary Grades Through Literature", 3),
          r("ELE18", "Research in Education", 3),
        ]),
        block(3, "SECOND", [
          r("PED03", "The Teacher and the Community, School Culture and Organizational Leadership", 3),
          r("ELE04", "Teaching Social Studies in the Elementary Grades (Culture and Geography)", 3),
          r("ELE06", "Pagtuturo ng Filipino sa Elementarya II (Panitikan ng Pilipinas)", 3),
          r("ELE10", "Edukasyong Pantahanan at Pangkabuhayan 2 with Entrepreneurship", 3),
          r("ELC01", "Teaching Multi-Grade Classes", 3),
        ]),
        block(4, "FIRST", [
          r("FS001", "Field Study 1", 3),
          r("FS002", "Field Study 2", 3),
          r("TCC01", "Integrative Course for Teaching", 3),
        ]),
        block(4, "SECOND", [
          r("PED11", "Teaching Internship", 6),
        ]),
      ],
    },
    {
      abbreviation: "BSEd-Sci",
      name: "Bachelor of Secondary Education Major in Sciences",
      blocks: [
        block(1, "FIRST", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
          r("PED01", "The Child and Adolescent Learners and Learning Principles", 3),
          r("CHM01", "Inorganic Chemistry", 3, 2),
        ]),
        block(1, "SECOND", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
          r("PED04", "Foundation of Special and Inclusive Education", 3),
          r("CHM02", "Organic Chemistry", 3, 2),
        ]),
        block(2, "FIRST", [
          r("GEC09", "Ethics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("PED02", "The Teaching Profession", 3),
          r("CHM03", "Biochemistry", 3),
          r("BIO01", "Genetics", 3, 1),
          r("PHY01", "Fluid Mechanics", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC07", "Art Appreciation", 3),
          r("GEL07", "Gender and Society", 3),
          r("PED03", "The Teacher and the Community, School Culture and Organizational Leadership", 3),
          r("PED10", "Building and Enhancing New Literacies Across the Curriculum", 3),
          r("CHM04", "Analytical Chemistry", 3, 2),
          r("PHY02", "Thermodynamics", 3, 1),
          r("PHY03", "Electricity and Magnetism", 3, 1),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("PED08", "Technology for Teaching and Learning 1", 3),
          r("PED06", "Assessment in Learning 1", 3),
          r("PED05", "Facilitating Learner-Centered Teaching", 3),
          r("BIO02", "Cell and Molecular Biology", 3, 1),
          r("SED01", "The Teaching of Science / Teaching the Specialized Field", 3),
          r("SED02", "Research in Teaching (Science)", 3),
          r("NSC01", "Earth Science", 3),
          r("BIO03", "Microbiology and Parasitology", 3, 1),
        ]),
        block(3, "SECOND", [
          r("NSC04", "Environmental Science", 3),
          r("PED07", "Assessment in Learning 2", 3),
          r("SED03", "Technology for Teaching and Learning 2", 3),
          r("PHY04", "Waves and Optics", 3, 1),
          r("BIO04", "Anatomy and Physiology", 3, 1),
          r("PHY05", "Modern Physics", 3),
          r("NSC02", "Astronomy", 3),
          r("NSC03", "Meteorology", 3),
        ]),
        block(4, "FIRST", [
          r("FS001", "Field Study 1", 3),
          r("FS002", "Field Study 2", 3),
          r("TCC01", "Integrative Course for Teaching", 3),
        ]),
        block(4, "SECOND", [
          r("PED11", "Teaching Internship", 6),
        ]),
      ],
    },
    {
      abbreviation: "BSEd-SS",
      name: "Bachelor of Secondary Education Major in Social Studies",
      blocks: [
        block(1, "FIRST", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
          r("PED01", "The Child and Adolescent Learners and Learning Principles", 3),
          r("FSE01", "Foundation of Social Studies", 3),
          r("SSE05", "Geography 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
          r("PED04", "Foundation of Special and Inclusive Education", 3),
          r("SSE06", "Geography 2", 3),
          r("SSE13", "Asian Studies", 3),
        ]),
        block(2, "FIRST", [
          r("GEC09", "Ethics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("PED02", "The Teaching Profession", 3),
          r("PED09", "The Teacher and the School Curriculum", 3),
          r("FSE04", "Places and Landscape in a Changing World", 3),
          r("SSE11", "World History I", 3),
          r("SSE08", "Micro Economics", 3),
          r("SSE03", "Socio-Cultural Anthropology", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC07", "Art Appreciation", 3),
          r("GEC12", "Dalumat ng/sa Filipino", 3),
          r("PED03", "The Teacher and the Community, School Culture and Organizational Leadership", 3),
          r("PED10", "Building and Enhancing New Literacies Across the Curriculum", 3),
          r("SSE09", "Macro Economics", 3),
          r("SSE07", "Geography 3", 3),
          r("SSE15", "Comparative Government and Politics", 3),
          r("SSE12", "World History 2", 3),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("PED08", "Technology for Teaching and Learning 1", 3),
          r("PED06", "Assessment in Learning 1", 3),
          r("PED05", "Facilitating Learner-Centered Teaching", 3),
          r("SSE20", "Teaching Approach in Secondary Social Studies Curriculum", 3),
          r("SSE21", "Assessment and Evaluation in the Social Science", 3),
          r("SSE14", "Comparative Economic Planning", 3),
          r("FSE02", "Research in Social Studies", 3),
        ]),
        block(3, "SECOND", [
          r("SSE23", "Law Related Studies", 3),
          r("PED07", "Assessment in Learning 2", 3),
          r("SSE25", "Technology for Teaching and Learning 2", 3),
          r("SSE22", "Production of Social Studies Instructional Materials", 3),
          r("SSE27", "Social Networking for Social Integration", 3),
          r("SSE24", "Integrative Methods in Teaching Social Science Discipline in Basic Education", 3),
          r("FSE03", "Trends and Issues in Social Studies", 3),
        ]),
        block(4, "FIRST", [
          r("FS001", "Field Study 1", 3),
          r("FS002", "Field Study 2", 3),
          r("TCC01", "Integrative Course for Teaching", 3),
          r("SSE26", "Human Resources Management", 3),
        ]),
        block(4, "SECOND", [
          r("PED11", "Teaching Internship", 6),
        ]),
      ],
    },
    {
      abbreviation: "BTLEd-HE",
      name: "Bachelor of Technology and Livelihood Education Major in Home Economics",
      blocks: [
        block(1, "FIRST", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("PED01", "The Child and Adolescent Learners and Learning Principles", 3),
          r("INA01", "Intro to Industrial Arts I", 3),
          r("ICT01", "Intro to ICT Specialization I", 2, 1),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PED04", "Foundation of Special and Inclusive Education", 3),
          r("INA02", "Intro to Industrial Arts II", 3),
          r("ICT02", "Intro to ICT Specialization II", 2, 1),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
        ]),
        block(2, "FIRST", [
          r("GEC09", "Ethics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("PED02", "The Teaching Profession", 3),
          r("PED03", "The Teacher and the Community, School Culture and Organizational Leadership", 3),
          r("HE001", "Home Economics Literacy", 3),
          r("HE002", "Family and Consumer Life Skills", 3),
          r("AF001", "Agri-Fishery I", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC07", "Art Appreciation", 3),
          r("GEC13", "Literature of the Philippines", 3),
          r("PED08", "Technology for Teaching and Learning 1", 3),
          r("PED10", "Building and Enhancing New Literacies Across the Curriculum", 3),
          r("PED05", "Facilitating Learner-Centered Teaching", 3),
          r("AF002", "Agri-Fishery II", 3),
          r("HEM01", "Household Resource Management", 2, 1),
          r("HEM02", "Consumer Education", 3),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("PED06", "Assessment in Learning 1", 3),
          r("TEC01", "Technology for Teaching and Learning 2", 3),
          r("PED09", "The Teacher and the School Curriculum", 3),
          r("RES01", "Methods of Research", 3),
          r("HEM03", "Principles of Food Preparation", 2, 1),
          r("HEM04", "Food and Nutrition", 2, 1),
          r("HEM05", "Fundamentals of Food Technology", 2, 1),
          r("HEM06", "School Food Service Management with 150 hrs. of Practicum Component", 2, 1),
          r("HEM07", "Child and Adolescent Development", 3, 1),
        ]),
        block(3, "SECOND", [
          r("PED07", "Assessment in Learning 2", 3),
          r("RES02", "Research 2", 3),
          r("HEM08", "Marriage and Family Relationships", 3),
          r("HEM09", "Clothing Selection, Purchases and Care", 3),
          r("HEM10", "Arts in Daily Living", 3, 1),
          r("HEM11", "Clothing Construction", 2, 1),
          r("HEM12", "Crafts Design (Handicraft)", 2, 1),
          r("ET001", "English for Technology", 3),
        ]),
        block(4, "FIRST", [
          r("FS001", "Field Study 1", 3),
          r("FS002", "Field Study 2", 3),
          r("TCC01", "Integrative Course for Teaching", 3),
        ]),
        block(4, "SECOND", [
          r("PED11", "Teaching Internship", 6),
        ]),
      ],
    },
    {
      abbreviation: "BSESS",
      name: "Bachelor of Science in Exercise and Sports Sciences Major in Fitness and Sports Coaching",
      blocks: [
        block(1, "FIRST", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("ESS01", "Philosophical and Socio-anthropological Foundations of Physical Education and Sports", 3),
          r("ESS02", "Anatomy of Human Movement and Performance", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("ESS03", "Principles of Motor Control and Learning of Exercise, Sports and Dance", 3),
          r("ESS04", "Coaching Theory and Practice in Exercise Science", 1),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
        ]),
        block(2, "FIRST", [
          r("GEC09", "Ethics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("ESS05", "Physiology of Exercise and Physical Activity", 3),
          r("ESS06", "Individual and Dual Sports I", 3),
          r("ESS07", "Movement Education", 3),
          r("ESS08", "Biomechanics", 3),
          r("ESS09", "Sports Ethics and Law", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC07", "Art Appreciation", 3),
          r("GEL07", "Gender and Society", 3),
          r("ESS10", "Assessment of Fitness and Sports Performance", 3),
          r("ESS11", "Team Sports I (Ball Games)", 3),
          r("ESS12", "Swimming and Aquatics", 3),
          r("ESS13", "Ergogenics and Healthy Eating in Exercise and Sports", 3),
          r("ESS14", "Musculoskeletal Fitness / Resistance Training Methods", 3),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("ESS15", "Cardiorespiratory / Aerobic Training Methods", 3),
          r("ESS16", "Contemporary Issues in Exercise and Sports", 3),
          r("ESS17", "Prevention and Management of Exercise and Sports-related Injuries", 3),
          r("ESS18", "Emergency Preparedness and Safety Management (Enhancement)", 3),
          r("ESS19", "Exercise Prescription and Programming", 3),
          r("ESS20", "Fundamentals of Management Practice (Elective)", 3),
          r("ESS21", "Research I", 3),
        ]),
        block(3, "SECOND", [
          r("ESS22", "Sports and Exercise Psychology", 3),
          r("ESS23", "Outdoor and Adventure Education", 3),
          r("ESS24", "Strength and Conditioning", 3),
          r("ESS25", "Stress Management (Elective)", 3),
          r("ESS26", "Coaching and Officiating Sports Events, Dance Competition and Music Activities (Enhancement)", 3),
          r("ESS27", "Research 2 (Applied Research in Exercise and Sports)", 3),
        ]),
        block(4, "FIRST", [
          r("ESS28", "Professional Preparation", 6),
        ]),
        block(4, "SECOND", [
          r("ESS29", "Internship (Industry Immersion)", 6),
        ]),
      ],
    },
    {
      abbreviation: "BTLEd-IA",
      name: "Bachelor of Technology and Livelihood Education Major in Industrial Arts",
      blocks: [
        block(1, "FIRST", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("PED01", "The Child and Adolescent Learners and Learning Principles", 3),
          r("INA01", "Intro to Industrial Arts I", 3),
          r("ICT01", "Intro to ICT Specialization I", 2, 1),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PED04", "Foundation of Special and Inclusive Education", 3),
          r("INA02", "Intro to Industrial Arts II", 3),
          r("ICT02", "Intro to ICT Specialization II", 2, 1),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
        ]),
        block(2, "FIRST", [
          r("GEC09", "Ethics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("PED02", "The Teaching Profession", 3),
          r("PED03", "The Teacher and the Community, School Culture and Organizational Leadership", 3),
          r("HE001", "Home Economics Literacy", 3),
          r("HE002", "Family and Consumer Life Skills", 3),
          r("AF001", "Agri-Fishery I", 3),
          r("ENT01", "Entrepreneurship", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC07", "Art Appreciation", 3),
          r("GEC13", "Literature of the Philippines", 3),
          r("PED08", "Technology for Teaching and Learning 1", 3),
          r("PED10", "Building and Enhancing New Literacies Across the Curriculum", 3),
          r("PED05", "Facilitating Learner-Centered Teaching", 3),
          r("AF002", "Agri-Fishery II", 3),
          r("IAM01", "Civil Technology 1", 2, 1),
          r("IAM02", "Civil Technology 2", 2, 1),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("PED06", "Assessment in Learning 1", 3),
          r("TEC01", "Technology for Teaching and Learning 2", 3),
          r("PED09", "The Teacher and the School Curriculum", 3),
          r("RES01", "Methods of Research", 3),
          r("IAM03", "Fundamentals of Automotive Technology", 2, 1),
          r("IAM04", "Fundamentals of Electronics Technology", 2, 1),
          r("IAM05", "Fundamentals of Electrical Technology", 2, 1),
          r("IAM06", "Domestic Refrigeration and Air Conditioning", 2, 1),
          r("IAM07", "Metal Works", 2, 1),
        ]),
        block(3, "SECOND", [
          r("PED07", "Assessment in Learning 2", 3),
          r("RES02", "Research 2", 3),
          r("IAM08", "Applied Automotive Technology", 2, 1),
          r("IAM09", "Digital Electronics Technology", 2, 1),
          r("IAM10", "Applied Electrical Technology", 2, 1),
          r("IAM11", "Commercial Refrigeration and Air Conditioning", 2, 1),
          r("IAM12", "Graphic Arts", 2, 1),
          r("ET001", "English for Technology", 3),
        ]),
        block(4, "FIRST", [
          r("FS001", "Field Study 1", 3),
          r("FS002", "Field Study 2", 3),
          r("TCC01", "Integrative Course for Teaching", 3),
        ]),
        block(4, "SECOND", [
          r("PED11", "Teaching Internship", 6),
        ]),
      ],
    },
    {
      abbreviation: "BTLEd-ICT",
      name: "Bachelor of Technology and Livelihood Education Major in Information and Communication Technology",
      blocks: [
        block(1, "FIRST", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("PED01", "The Child and Adolescent Learners and Learning Principles", 3),
          r("INA01", "Intro to Industrial Arts I", 3),
          r("ICT01", "Intro to ICT Specialization I", 2, 1),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
        ]),
        block(1, "SECOND", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PED04", "Foundation of Special and Inclusive Education", 3),
          r("INA02", "Intro to Industrial Arts II", 3),
          r("ICT02", "Intro to ICT Specialization II", 2, 1),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
        ]),
        block(2, "FIRST", [
          r("GEC09", "Ethics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("PED02", "The Teaching Profession", 3),
          r("PED03", "The Teacher and the Community, School Culture and Organizational Leadership", 3),
          r("HE001", "Home Economics Literacy", 3),
          r("HE002", "Family and Consumer Life Skills", 3),
          r("ICTM01", "Drawing Tools and Materials", 2, 1),
          r("ICTM02", "Drawing Concepts and Strategies", 2, 1),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC07", "Art Appreciation", 3),
          r("GEC13", "Literature of the Philippines", 3),
          r("PED08", "Technology for Teaching and Learning 1", 3),
          r("PED10", "Building and Enhancing New Literacies Across the Curriculum", 3),
          r("PED05", "Facilitating Learner-Centered Teaching", 3),
          r("AF001", "Agri-Fishery I", 3),
          r("ICTM03", "Troubleshooting Techniques", 2, 1),
          r("ICTM04", "2D Animation - Key Drawings", 2, 1),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("PED06", "Assessment in Learning 1", 3),
          r("TEC01", "Technology for Teaching and Learning 2", 3),
          r("ENT01", "Entrepreneurship", 3),
          r("RES01", "Methods of Research", 3),
          r("ICTM05", "2D Digital Animation", 2, 1),
          r("ICTM06", "2D Animation - Authoring Tools", 2, 1),
          r("ICTM07", "Website Creation", 2, 1),
          r("AF002", "Agri-Fishery II", 3),
          r("ICTM08", "Internet Marketing", 2, 1),
        ]),
        block(3, "SECOND", [
          r("PED07", "Assessment in Learning 2", 3),
          r("RES02", "Research 2", 3),
          r("ICTM09", "Author Wares", 2, 1),
          r("ICTM10", "Video Production", 2, 1),
          r("ICTM11", "Audio Production", 2, 1),
          r("ICTM12", "Print Production", 2, 1),
          r("ET001", "English for Technology", 3),
          r("PED09", "The Teacher and the School Curriculum", 3),
        ]),
        block(4, "FIRST", [
          r("FS001", "Field Study 1", 3),
          r("FS002", "Field Study 2", 3),
          r("TCC01", "Integrative Course for Teaching", 3),
        ]),
        block(4, "SECOND", [
          r("PED11", "Teaching Internship", 6),
        ]),
      ],
    },
    {
      abbreviation: "BSEd-Eng",
      name: "Bachelor of Secondary Education Major in English",
      blocks: [
        block(1, "FIRST", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
          r("PED01", "The Child and Adolescent Learners and Learning Principles", 3),
          r("LIN01", "Introduction to Linguistics", 3),
        ]),
        block(1, "SECOND", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
          r("PED04", "Foundation of Special and Inclusive Education", 3),
          r("LIN02", "Language, Culture and Society", 3),
        ]),
        block(2, "FIRST", [
          r("GEC09", "Ethics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("PED02", "The Teaching Profession", 3),
          r("PED09", "The Teacher and the School Curriculum", 3),
          r("LIN03", "Structure of English", 3),
          r("ELT01", "Principles and Theories of Language Acquisition and Learning", 3),
          r("ELT05", "Teaching and Assessment of the Macroskills", 3),
          r("LTE01", "Children and Adolescent Literature", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC07", "Art Appreciation", 3),
          r("GEC12", "Dalumat ng/sa Filipino", 3),
          r("GEC13", "Literature of the Philippines", 3),
          r("PED03", "The Teacher and the Community, School Culture and Organizational Leadership", 3),
          r("PED10", "Building and Enhancing New Literacies Across the Curriculum", 3),
          r("ELT02", "Language Programs and Policies in Multilingual Societies", 3),
          r("LTE02", "Mythology and Folklore", 3),
          r("LTE03", "Survey of Philippine Literature in English", 3),
          r("ELT06", "Teaching and Assessment of Grammar", 3),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("PED08", "Technology for Teaching and Learning 1", 3),
          r("PED06", "Assessment in Learning 1", 3),
          r("PED05", "Facilitating Learner-Centered Teaching", 3),
          r("GEC14", "Literature of the World", 3),
          r("LTE04", "Survey of Afro-Asian Literature", 3),
          r("LTE05", "Survey of English-American Literature", 3),
          r("ELT07", "Speech and Theatre Arts", 3),
          r("ELT03", "Language Learning Materials Development", 3),
          r("ELT09", "Technical Writing", 3),
        ]),
        block(3, "SECOND", [
          r("ELT11", "Technology for Teaching and Learning 2", 3),
          r("PED07", "Assessment in Learning 2", 3),
          r("LTE06", "Contemporary, Popular and Emergent Literature", 3),
          r("ELT04", "Teaching and Assessment of Literature Studies", 3),
          r("ELT08", "Language Education Research", 3),
          r("LTE07", "Literary Criticism", 3),
          r("ELT10", "Campus Journalism", 3),
          r("ELT12", "Stylistics and Discourse Analysis", 3),
          r("ELT13", "English for Specific Purposes", 3),
        ]),
        block(4, "FIRST", [
          r("FS001", "Field Study 1", 3),
          r("FS002", "Field Study 2", 3),
          r("TCC01", "Integrative Course for Teaching", 3),
        ]),
        block(4, "SECOND", [
          r("PED11", "Teaching Internship", 6),
        ]),
      ],
    },
    {
      abbreviation: "BSEd-Fil",
      name: "Bachelor of Secondary Education Major in Filipino",
      blocks: [
        block(1, "FIRST", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
          r("PED01", "The Child and Adolescent Learners and Learning Principles", 3),
          r("FIL01", "Introduksyon sa Pag-aaral ng Wika", 3),
          r("FIL02", "Panimulang Linggwistika", 3),
        ]),
        block(1, "SECOND", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC03", "Readings in Philippine History", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
          r("PED04", "Foundation of Special and Inclusive Education", 3),
          r("PAN01", "Panitikan ng Rehiyon", 3),
          r("FIL04", "Estruktura ng Wikang Filipino", 3),
        ]),
        block(2, "FIRST", [
          r("GEC09", "Ethics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("PED02", "The Teaching Profession", 3),
          r("PED09", "The Teacher and the School Curriculum", 3),
          r("FIL03", "Ang Filipino sa Kurikulum ng Batayang Edukasyon", 3),
          r("FIL05", "Pagtuturo at Pagtataya ng Makrong Kasanayang Pangwika", 3),
          r("FIL07", "Paghahanda at Ebalwasyon ng Kagamitang Panturo", 3),
          r("FIL08", "Introduksyon sa Pagsasalin", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC07", "Art Appreciation", 3),
          r("GEC13", "Literature of the Philippines", 3),
          r("PED03", "The Teacher and the Community, School Culture and Organizational Leadership", 3),
          r("PED10", "Building and Enhancing New Literacies Across the Curriculum", 3),
          r("FIL12", "Sanaysay at Talumpati", 3),
          r("PAN03", "Balangayang Edukasyon sa Panitikan", 3),
          r("PAN04", "Panunuring Pampanitikan", 3),
          r("EAF01", "Pagsasalin sa Iba't Ibang Disiplina (Elective)", 3),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("PED08", "Technology for Teaching and Learning 1", 3),
          r("PED06", "Assessment in Learning 1", 3),
          r("PED05", "Facilitating Learner-Centered Teaching", 3),
          r("FIL09", "Introduksyon sa Pananaliksik - Wika at Panitikan", 3),
          r("FIL10", "Panimulang Pananaliksik sa Wika", 3),
          r("FIL11", "Barayti at Baryasyon ng Wika", 3),
          r("PAN02", "Kulturang Popular", 3),
        ]),
        block(3, "SECOND", [
          r("FIL06", "Ugnayan ng Wika, Kultura at Lipunan", 3),
          r("PED07", "Assessment in Learning 2", 3),
          r("FIL13", "Technology for Teaching and Learning 2", 3),
          r("PAN06", "Panulaang Filipino", 3),
          r("PAN07", "Dulang Filipino", 3),
          r("PAN05", "Maikling Kwento at Nobelang Filipino", 3),
          r("EAF02", "Malikhaing Pagsulat (Elective)", 3),
        ]),
        block(4, "FIRST", [
          r("FS001", "Field Study 1", 3),
          r("FS002", "Field Study 2", 3),
          r("TCC01", "Integrative Course for Teaching", 3),
        ]),
        block(4, "SECOND", [
          r("PED11", "Teaching Internship", 6),
        ]),
      ],
    },
    {
      abbreviation: "BSEd-Math",
      name: "Bachelor of Secondary Education Major in Mathematics",
      blocks: [
        block(1, "FIRST", [
          r("GEC01", "The Life and Works of Rizal", 3),
          r("GEC04", "The Contemporary World", 3),
          r("GEC08", "Science, Technology and Society", 3),
          r("GEC10", "Kontekstwalisadong Komunikasyon sa Filipino", 3),
          r("PATHFit01", "Movement Skill Training", 2),
          r("NSTP1", "National Service Training Program 1", 3),
          r("PED01", "The Child and Adolescent Learners and Learning Principles", 3),
          r("MAT01", "College and Advanced Algebra", 3),
          r("MAT12", "Logic and Set Theory", 3),
        ]),
        block(1, "SECOND", [
          r("GEC02", "Understanding the Self", 3),
          r("GEC05", "Mathematics in the Modern World", 3),
          r("GEC06", "Purposive Communication", 3),
          r("PATHFit02", "Fitness and Wellness Activities", 2),
          r("NSTP2", "National Service Training Program 2", 3),
          r("PED04", "Foundation of Special and Inclusive Education", 3),
          r("MAT08", "History of Mathematics", 3),
          r("MAT02", "Trigonometry", 3),
          r("MAT03", "Plane and Solid Geometry", 3),
        ]),
        block(2, "FIRST", [
          r("GEC09", "Ethics", 3),
          r("GEC11", "Filipino sa Iba't Ibang Disiplina", 3),
          r("PED02", "The Teaching Profession", 3),
          r("PED09", "The Teacher and the School Curriculum", 3),
          r("MAT04b", "Calculus 1 with Analytic Geometry", 4),
          r("MAT27", "Modern Geometry", 3),
          r("STA04", "Elementary Statistics and Probability", 3),
          r("PATHFit03", "Rhythmic Activities and/or Sports", 2),
        ]),
        block(2, "SECOND", [
          r("GEC07", "Art Appreciation", 3),
          r("GEL04", "Living in the IT Era", 3),
          r("PED03", "The Teacher and the Community, School Culture and Organizational Leadership", 3),
          r("PED10", "Building and Enhancing New Literacies Across the Curriculum", 3),
          r("STA05", "Advanced Statistics", 3),
          r("MAT05a", "Calculus 2", 4),
          r("MAT17", "Number Theory", 3),
          r("PATHFit04", "Recreational Activities", 2),
        ]),
        block(3, "FIRST", [
          r("PED08", "Technology for Teaching and Learning 1", 3),
          r("PED06", "Assessment in Learning 1", 3),
          r("PED05", "Facilitating Learner-Centered Teaching", 3),
          r("MAT06a", "Calculus 3", 3),
          r("MAT18", "Principles and Strategies of Teaching Mathematics", 3),
          r("MAT19", "Research in Mathematics", 4),
        ]),
        block(3, "SECOND", [
          r("GEC03", "Readings in Philippine History", 3),
          r("PED07", "Assessment in Learning 2", 3),
          r("MAT13", "Mathematics of Investment", 3),
          r("MAT15", "Abstract Algebra", 3),
          r("MAT20", "Problem Solving, Mathematical Investigation and Modeling", 3),
          r("MAT116", "Linear Algebra", 3),
          r("MAT121", "Assessment and Evaluation in Mathematics", 3),
        ]),
        block(4, "FIRST", [
          r("FS001", "Field Study 1", 3),
          r("FS002", "Field Study 2", 3),
          r("TCC01", "Integrative Course for Teaching", 3),
          r("MAT22", "Technology for Teaching and Learning 2 - Instrumentation and Technology in Mathematics Software Applications", 3),
          r("MAE01", "Data Analysis with Computer Software Applications", 3),
        ]),
        block(4, "SECOND", [
          r("PED11", "Teaching Internship", 6),
        ]),
      ],
    },
  ],
}
